name: WIF
env:
  project_id: db-cicdpipeline-wave-2
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  wif:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Auth Google cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: "projects/817731629023/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "my-service-account@db-cicdpipeline-wave-2.iam.gserviceaccount.com"
      - name: List bucket
        run: |
          gcloud compute instances list --project ${{ env.project_id }}
